export const ROLE_PERMISSION_MATRIX: Record<string, string[]> = {
  Worker: [
    'view_dashboard',
    'view_profile',
    'edit_profile',
    'change_password',
    'view_attendance_own',
    'mark_attendance',
    'request_attendance_correction',
    'apply_leave',
    'request_leave',
    'view_leave_own',
    'view_payslip_own',
    'download_payslip',
    'view_holidays',
    'view_announcements',
    'view_tasks',
    'view_shift_schedule',
    'view_expense_claims_own',
    'submit_reimbursement',
    'raise_support_ticket',
    'view_performance_own',
    'upload_documents'
  ],
  Employee: [
    'view_dashboard',
    'view_profile',
    'edit_profile',
    'change_password',
    'view_attendance_own',
    'mark_attendance',
    'request_attendance_correction',
    'apply_leave',
    'request_leave',
    'view_leave_own',
    'view_payslip_own',
    'download_payslip',
    'view_holidays',
    'view_announcements',
    'view_tasks',
    'view_shift_schedule',
    'view_expense_claims_own',
    'submit_reimbursement',
    'raise_support_ticket',
    'view_performance_own',
    'upload_documents'
  ],
  Manager: [
    'view_dashboard',
    'view_profile',
    'edit_profile',
    'change_password',
    'view_attendance_own',
    'view_attendance',
    'view_attendance_team',
    'approve_attendance',
    'manage_attendance',
    'request_attendance_correction',
    'view_leave',
    'view_leave_team',
    'approve_leave',
    'reject_leave',
    'view_payslip_own',
    'download_payslip',
    'view_holidays',
    'view_announcements',
    'view_tasks',
    'assign_tasks',
    'view_shift_schedule',
    'view_expense_claims_own',
    'approve_expenses',
    'view_project_allocation',
    'view_employee',
    'view_performance_team',
    'conduct_appraisals',
    'recommend_promotions',
    'view_performance_own',
    'raise_support_ticket'
  ],
  HR: ['*'],
  Admin: ['*'],
  'Super Admin': ['*'],
  CEO: [
    'view_dashboard',
    'view_profile',
    'edit_profile',
    'change_password',
    'view_attendance',
    'view_leave',
    'view_payroll',
    'view_employee',
    'view_audit_logs',
    'view_performance_team',
    'view_performance_own',
    'view_holidays',
    'view_announcements',
    'view_tasks',
    'view_project_allocation',
    'view_shift_schedule',
    'view_expense_claims_own',
    'raise_support_ticket'
  ]
};

export function normalizeRole(role?: string | null) {
  return (role ?? '').trim();
}

export function getPermissionsForRole(role?: string | null): string[] {
  return ROLE_PERMISSION_MATRIX[normalizeRole(role)] ?? [];
}